#!/usr/bin/env python3
"""Differential tests for canforge's generated code.

  harness.py c <file.dbc> <prefix> <out_dir> [vectors]
      Writes <out_dir>/<prefix>_harness.c. It packs and unpacks random frames
      with the generated C and compares every byte and field against the
      reference model, which packs one bit at a time and shares no code with
      the generated byte-wise shift/mask logic.

  harness.py py <file.dbc> <generated.py> [frames]
      Imports a generated Python decoder and checks it against the reference
      model's decode() on random frames.

Both use a fixed seed so failures are reproducible.
"""

import importlib.util
import math
import random
import struct
import sys

import canforge_ref as ref

SEED = 20260917


def random_raw(rng, s):
    """A random raw value for a signal, biased toward edge cases."""
    if s.value_type == "float32":
        f = rng.choice([0.0, -0.0, 1.0, -1.5, 3.4e38, -3.4e38, 1e-38, rng.uniform(-1e6, 1e6)])
        return struct.unpack("<I", struct.pack("<f", f))[0]
    if s.value_type == "float64":
        f = rng.choice([0.0, 1.0, -2.5, 1.7e308, rng.uniform(-1e12, 1e12)])
        return struct.unpack("<Q", struct.pack("<d", f))[0]
    lo, hi = ref.raw_range(s.length, s.signed)
    pick = rng.random()
    if pick < 0.08:
        return lo
    if pick < 0.16:
        return hi
    if pick < 0.20 and lo <= 0 <= hi:
        return 0
    if pick < 0.24 and lo <= -1:
        return -1
    return rng.randint(lo, hi)


def c_literal(value, s):
    if s.value_type != "integer" or not s.signed:
        return "%dull" % value
    if value == -(1 << 63):
        return "(-9223372036854775807LL - 1LL)"
    return "%dLL" % value


def frame_case(rng, m, mux_choice):
    """Return (pack_input, expected_unpack, frame_bytes) as raw dicts and bytes."""
    plain, groups, mux_sig = ref.split_groups(m)
    data = bytearray(m.dlc)
    pack_in = {}
    unpack_out = {}
    active = None
    if mux_sig is not None:
        active = mux_choice
    for s in m.signals:
        if isinstance(s.mux, int):
            raw = random_raw(rng, s)
            pack_in[id(s)] = raw
            if s.mux == active:
                unpack_out[id(s)] = raw
                ref.insert_raw(data, s, raw)
            else:
                unpack_out[id(s)] = 0
        else:
            raw = active if s is mux_sig else random_raw(rng, s)
            pack_in[id(s)] = raw
            unpack_out[id(s)] = raw
            ref.insert_raw(data, s, raw)
    return pack_in, unpack_out, bytes(data)


def physical_bounds_check(s, raw):
    """Independent opinion on is_in_range: True, False, or None near a boundary."""
    if ref.is_unspecified_range(s):
        return True
    phys = float(raw) * s.factor + s.offset
    eps = 1e-6 * max(1.0, abs(s.minimum), abs(s.maximum), abs(s.factor))
    if phys < s.minimum - eps or phys > s.maximum + eps:
        return False
    if s.minimum + eps <= phys <= s.maximum - eps:
        return True
    return None


def gen_c_harness(db, prefix, vectors):
    rng = random.Random(SEED)
    names = ref.Names(db)
    out = []
    out.append("/* Generated by reference/harness.py. Differential test of %s.c */" % prefix)
    out.append("#include <stdio.h>")
    out.append("#include <string.h>")
    out.append('#include "%s.h"' % prefix)
    out.append("")
    out.append("static unsigned long checks = 0;")
    out.append("static unsigned long failures = 0;")
    out.append("")
    out.append("static void check(int ok, const char *what, unsigned long index)")
    out.append("{")
    out.append("    checks++;")
    out.append("    if (!ok) {")
    out.append("        failures++;")
    out.append("        if (failures <= 25) {")
    out.append('            printf("FAIL %s (vector %lu)\\n", what, index);')
    out.append("        }")
    out.append("    }")
    out.append("}")
    calls = []
    for mi, m in enumerate(db.messages):
        mname = names.msg[mi]
        typ = "%s_%s_t" % (prefix, mname)
        plain, groups, mux_sig = ref.split_groups(m)
        cases = []
        choices = [g[0] for g in groups]
        for k in range(vectors):
            mux_choice = None
            if mux_sig is not None:
                lo, hi = ref.raw_range(mux_sig.length, mux_sig.signed)
                if choices and k % 5 != 4:
                    mux_choice = choices[k % len(choices)]
                else:
                    mux_choice = rng.randint(lo, hi)
            cases.append(frame_case(rng, m, mux_choice))
        width = max(m.dlc, 1)
        out.append("")
        out.append("/* %s */" % m.name)
        out.append("static const unsigned char %s_bytes[%d][%d] = {" % (mname, vectors, width))
        for _, _, data in cases:
            row = data if data else b"\x00"
            out.append("    {%s}," % ", ".join("0x%02X" % b for b in row))
        out.append("};")
        for label, idx in (("in", 0), ("out", 1)):
            out.append("static const %s %s_%s[%d] = {" % (typ, mname, label, vectors))
            for case in cases:
                vals = case[idx]
                fields = []
                for si, s in enumerate(m.signals):
                    fields.append(".%s = %s" % (names.sig[mi][si], c_literal(vals[id(s)], s)))
                if not fields:
                    fields.append(".unused = 0u")
                out.append("    {%s}," % ", ".join(fields))
            out.append("};")

        fn = "test_%s" % mname
        calls.append(fn)
        out.append("")
        out.append("static void %s(void)" % fn)
        out.append("{")
        out.append("    unsigned long i;")
        out.append("    unsigned char buf[%d];" % width)
        out.append("    %s got;" % typ)
        out.append("")
        out.append("    for (i = 0; i < %dul; i++) {" % vectors)
        out.append("        int n = %s_%s_pack(buf, &%s_in[i], sizeof(buf));" % (prefix, mname, mname))
        out.append('        check(n == %d, "%s pack returns length", i);' % (m.dlc, m.name))
        if m.dlc > 0:
            out.append('        check(memcmp(buf, %s_bytes[i], %d) == 0, "%s pack bytes", i);' % (mname, m.dlc, m.name))
        out.append("        n = %s_%s_unpack(&got, %s_bytes[i], %d);" % (prefix, mname, mname, m.dlc))
        out.append('        check(n == 0, "%s unpack returns 0", i);' % m.name)
        for si, s in enumerate(m.signals):
            f = names.sig[mi][si]
            out.append('        check(got.%s == %s_out[i].%s, "%s.%s unpack", i);' % (f, mname, f, m.name, s.name))
            sig_fn = "%s_%s_%s" % (prefix, mname, f)
            if s.value_type == "integer":
                big = s.length > 50
                guard = ""
                if big and s.signed:
                    guard = "if (got.%s > -(1LL << 50) && got.%s < (1LL << 50)) " % (f, f)
                elif big:
                    guard = "if (got.%s < (1ull << 50)) " % f
                out.append('        %scheck(%s_encode(%s_decode(got.%s)) == got.%s, "%s.%s encode(decode(raw)) round trip", i);'
                           % (guard, sig_fn, sig_fn, f, f, m.name, s.name))
            else:
                out.append('        check(%s_encode(%s_decode(got.%s)) == got.%s, "%s.%s float round trip", i);'
                           % (sig_fn, sig_fn, f, f, m.name, s.name))
        out.append("    }")
        if m.dlc > 0:
            out.append("    (void)memset(&got, 0, sizeof(got));")
            out.append('    check(%s_%s_pack(buf, &got, %d) == -1, "%s pack rejects short buffer", 0ul);' % (prefix, mname, m.dlc - 1, m.name))
            out.append('    check(%s_%s_unpack(&got, buf, %d) == -1, "%s unpack rejects short buffer", 0ul);' % (prefix, mname, m.dlc - 1, m.name))

        # is_in_range against an independent physical-range opinion
        for si, s in enumerate(m.signals):
            if s.value_type != "integer":
                continue
            f = names.sig[mi][si]
            sig_fn = "%s_%s_%s" % (prefix, mname, f)
            lo, hi = ref.raw_range(s.length, s.signed)
            probes = [lo, hi, 0 if lo <= 0 <= hi else lo]
            for _ in range(12):
                probes.append(rng.randint(lo, hi))
            for raw in probes:
                expect = physical_bounds_check(s, raw)
                if expect is None:
                    continue
                out.append('    check(%s_is_in_range(%s) == %s, "%s.%s is_in_range(%d)", 0ul);'
                           % (sig_fn, c_literal(raw, s), "true" if expect else "false", m.name, s.name, raw))
        out.append("}")

    out.append("")
    out.append("int main(void)")
    out.append("{")
    for fn in calls:
        out.append("    %s();" % fn)
    out.append('    printf("%lu checks, %lu failures\\n", checks, failures);')
    out.append("    return failures == 0 ? 0 : 1;")
    out.append("}")
    out.append("")
    return "\n".join(out)


def check_python(db, path, frames):
    spec = importlib.util.spec_from_file_location("generated_decoder", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    rng = random.Random(SEED)
    checked = 0
    for m in db.messages:
        plain, groups, mux_sig = ref.split_groups(m)
        choices = [g[0] for g in groups]
        for k in range(frames):
            mux_choice = None
            if mux_sig is not None:
                lo, hi = ref.raw_range(mux_sig.length, mux_sig.signed)
                mux_choice = choices[k % len(choices)] if choices and k % 5 != 4 else rng.randint(lo, hi)
            _, _, data = frame_case(rng, m, mux_choice)
            expected = ref.decode(db, m.frame_id, data, m.is_extended)
            got = mod.decode(m.frame_id, data, m.is_extended)
            want = {r["name"]: r["physical"] for r in expected["signals"]}
            if set(got) != set(want):
                raise SystemExit("FAIL %s: signal sets differ: %s vs %s" % (m.name, sorted(got), sorted(want)))
            for name, value in want.items():
                g = got[name]
                same = (g == value) or (math.isnan(g) and math.isnan(value))
                if not same:
                    raise SystemExit("FAIL %s.%s: generated %r, reference %r (frame %s)" % (m.name, name, g, value, data.hex()))
                checked += 1
    try:
        mod.decode(0x7FF, b"\x00" * 8, False)
        raise SystemExit("FAIL: unknown frame ID was accepted")
    except mod.DecodeError:
        pass
    print("%d signal values identical across %d messages" % (checked, len(db.messages)))


def main(argv):
    if len(argv) >= 5 and argv[1] == "c":
        db = ref.parse_file(argv[2])
        vectors = int(argv[5]) if len(argv) > 5 else 300
        text = gen_c_harness(db, argv[3], vectors)
        with open("%s/%s_harness.c" % (argv[4], argv[3]), "w") as f:
            f.write(text)
        return 0
    if len(argv) >= 4 and argv[1] == "py":
        db = ref.parse_file(argv[2])
        frames = int(argv[4]) if len(argv) > 4 else 500
        check_python(db, argv[3], frames)
        return 0
    print(__doc__, file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
