"""Decoders for powertrain.dbc.

Generated by canforge 0.1.0. Do not edit.
https://github.com/Swaraj-Patil/canforge

Each decode_* function takes the frame payload as bytes and returns a
dict of physical values keyed by signal name. Multiplexed signals are
only present when their multiplexer selects them.
"""

import struct


class DecodeError(ValueError):
    """Raised when a frame cannot be decoded."""


def decode_vehicle_status(data):
    """Decode VehicleStatus (frame 0x100, standard, 8 bytes)."""
    if len(data) < 8:
        raise DecodeError("VehicleStatus needs 8 bytes, got %d" % len(data))
    values = {}
    v = 0
    v |= data[0]
    v |= (data[1] << 8)
    values["VehicleSpeed"] = v * 0.01
    v = 0
    v |= (data[2] & 0x7)
    values["GearPosition"] = float(v)
    v = 0
    v |= ((data[2] >> 3) & 0x1)
    values["BrakePressed"] = float(v)
    v = 0
    v |= ((data[2] >> 4) & 0x3)
    values["DriveMode"] = float(v)
    v = 0
    v |= data[3]
    values["AcceleratorPedal"] = v * 0.4
    v = 0
    v |= data[4]
    v |= (data[5] << 8)
    if v & 0x8000:
        v -= 0x10000
    values["SteeringAngle"] = v * 0.1
    v = 0
    v |= (data[7] & 0xF)
    values["RollingCounter"] = float(v)
    v = 0
    v |= ((data[7] >> 4) & 0xF)
    values["Checksum"] = float(v)
    return values


def decode_battery_status(data):
    """Decode BatteryStatus (frame 0x200, standard, 8 bytes)."""
    if len(data) < 8:
        raise DecodeError("BatteryStatus needs 8 bytes, got %d" % len(data))
    values = {}
    v = 0
    v |= (data[0] << 8)
    v |= data[1]
    values["PackVoltage"] = v * 0.01
    v = 0
    v |= (data[2] << 8)
    v |= data[3]
    if v & 0x8000:
        v -= 0x10000
    values["PackCurrent"] = v * 0.05
    v = 0
    v |= data[4]
    values["StateOfCharge"] = v * 0.5
    v = 0
    v |= data[5]
    if v & 0x80:
        v -= 0x100
    values["MaxCellTemp"] = float(v)
    v = 0
    v |= ((data[6] >> 6) & 0x3)
    values["ContactorState"] = float(v)
    v = 0
    v |= ((data[6] >> 5) & 0x1)
    values["BalancingActive"] = float(v)
    v = 0
    v |= (data[6] & 0x1F)
    values["CellCount"] = float(v)
    return values


def decode_inverter_telemetry(data):
    """Decode InverterTelemetry (frame 0x300, standard, 8 bytes)."""
    if len(data) < 8:
        raise DecodeError("InverterTelemetry needs 8 bytes, got %d" % len(data))
    values = {}
    v = 0
    v |= data[0]
    mux = v
    values["PageIndex"] = float(v)
    v = 0
    v |= (data[7] & 0x7)
    values["InverterState"] = float(v)
    if mux == 0:
        v = 0
        v |= data[1]
        v |= (data[2] << 8)
        if v & 0x8000:
            v -= 0x10000
        values["MotorSpeed"] = float(v)
        v = 0
        v |= data[3]
        v |= (data[4] << 8)
        if v & 0x8000:
            v -= 0x10000
        values["MotorTorque"] = v * 0.1
    elif mux == 1:
        v = 0
        v |= data[1]
        values["StatorTemp"] = float(v) - 40.0
        v = 0
        v |= data[2]
        values["IgbtTemp"] = float(v) - 40.0
    elif mux == 2:
        v = 0
        v |= data[1]
        v |= (data[2] << 8)
        values["DcLinkVoltage"] = v * 0.1
        v = 0
        v |= data[3]
        v |= (data[4] << 8)
        values["FaultCode"] = float(v)
    return values


def decode_charger_limits(data):
    """Decode ChargerLimits (frame 0x18FF50E5, extended, 8 bytes)."""
    if len(data) < 8:
        raise DecodeError("ChargerLimits needs 8 bytes, got %d" % len(data))
    values = {}
    v = 0
    v |= data[0]
    v |= (data[1] << 8)
    values["ChargeCurrentLimit"] = v * 0.1
    v = 0
    v |= data[2]
    v |= (data[3] << 8)
    values["ChargeVoltageLimit"] = v * 0.1
    v = 0
    v |= (data[4] & 0x1)
    values["ChargerEnable"] = float(v)
    return values


def decode_thermal_sensors(data):
    """Decode ThermalSensors (frame 0x400, standard, 8 bytes)."""
    if len(data) < 8:
        raise DecodeError("ThermalSensors needs 8 bytes, got %d" % len(data))
    values = {}
    v = 0
    v |= data[0]
    v |= (data[1] << 8)
    v |= (data[2] << 16)
    v |= (data[3] << 24)
    values["CoolantFlow"] = struct.unpack("<f", v.to_bytes(4, "little"))[0]
    v = 0
    v |= data[4]
    v |= (data[5] << 8)
    v |= (data[6] << 16)
    v |= (data[7] << 24)
    values["AmbientTemp"] = struct.unpack("<f", v.to_bytes(4, "little"))[0]
    return values


def decode_wheel_speeds(data):
    """Decode WheelSpeeds (frame 0x600, standard, 8 bytes)."""
    if len(data) < 8:
        raise DecodeError("WheelSpeeds needs 8 bytes, got %d" % len(data))
    values = {}
    v = 0
    v |= (data[0] << 4)
    v |= ((data[1] >> 4) & 0xF)
    values["WheelSpeedFL"] = v * 0.1
    v = 0
    v |= ((data[1] & 0xF) << 8)
    v |= data[2]
    values["WheelSpeedFR"] = v * 0.1
    v = 0
    v |= (data[3] << 4)
    v |= ((data[4] >> 4) & 0xF)
    values["WheelSpeedRL"] = v * 0.1
    v = 0
    v |= ((data[4] & 0xF) << 8)
    v |= data[5]
    values["WheelSpeedRR"] = v * 0.1
    v = 0
    v |= data[6]
    v |= ((data[7] & 0x3F) << 8)
    if v & 0x2000:
        v -= 0x4000
    values["YawRate"] = v * 0.01
    v = 0
    v |= ((data[7] >> 6) & 0x3)
    values["WheelSpeedValid"] = float(v)
    return values


def decode_diagnostic_fd(data):
    """Decode DiagnosticFD (frame 0x500, standard, 64 bytes)."""
    if len(data) < 64:
        raise DecodeError("DiagnosticFD needs 64 bytes, got %d" % len(data))
    values = {}
    v = 0
    v |= data[0]
    v |= (data[1] << 8)
    v |= (data[2] << 16)
    v |= (data[3] << 24)
    values["Odometer"] = v * 0.1
    v = 0
    v |= data[4]
    v |= (data[5] << 8)
    v |= (data[6] << 16)
    v |= (data[7] << 24)
    values["TripId"] = float(v)
    v = 0
    v |= data[8]
    v |= (data[9] << 8)
    v |= (data[10] << 16)
    v |= (data[11] << 24)
    v |= (data[12] << 32)
    v |= (data[13] << 40)
    v |= (data[14] << 48)
    v |= (data[15] << 56)
    values["SerialNumber"] = float(v)
    v = 0
    v |= data[16]
    v |= (data[17] << 8)
    v |= (data[18] << 16)
    v |= (data[19] << 24)
    values["FirmwareCrc"] = float(v)
    v = 0
    v |= (data[23] << 40)
    v |= (data[24] << 32)
    v |= (data[25] << 24)
    v |= (data[26] << 16)
    v |= (data[27] << 8)
    v |= data[28]
    values["LifetimeEnergy"] = v * 0.001
    v = 0
    v |= data[32]
    v |= (data[33] << 8)
    v |= (data[34] << 16)
    v |= (data[35] << 24)
    v |= (data[36] << 32)
    v |= (data[37] << 40)
    v |= (data[38] << 48)
    v |= (data[39] << 56)
    if v & 0x8000000000000000:
        v -= 0x10000000000000000
    values["TimestampNs"] = float(v)
    return values


DECODERS = {
    (0x100, False): decode_vehicle_status,
    (0x200, False): decode_battery_status,
    (0x300, False): decode_inverter_telemetry,
    (0x18FF50E5, True): decode_charger_limits,
    (0x400, False): decode_thermal_sensors,
    (0x600, False): decode_wheel_speeds,
    (0x500, False): decode_diagnostic_fd,
}

MESSAGE_NAMES = {
    (0x100, False): "VehicleStatus",
    (0x200, False): "BatteryStatus",
    (0x300, False): "InverterTelemetry",
    (0x18FF50E5, True): "ChargerLimits",
    (0x400, False): "ThermalSensors",
    (0x600, False): "WheelSpeeds",
    (0x500, False): "DiagnosticFD",
}


def decode(frame_id, data, is_extended=False):
    """Decode a frame by ID. Raises DecodeError for unknown frames."""
    fn = DECODERS.get((frame_id, is_extended))
    if fn is None:
        raise DecodeError("unknown frame ID 0x%X" % frame_id)
    return fn(bytes(data))
