/**
 * powertrain.c
 *
 * Generated by canforge 0.1.0 from powertrain.dbc. Do not edit.
 * https://github.com/Swaraj-Patil/canforge
 */

#include <float.h>
#include <string.h>

#include "powertrain.h"

void powertrain_vehicle_status_init(powertrain_vehicle_status_t *msg_p)
{
    (void)memset(msg_p, 0, sizeof(*msg_p));
}

int powertrain_vehicle_status_pack(uint8_t *dst_p, const powertrain_vehicle_status_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 8u) {
        return -1;
    }

    (void)memset(dst_p, 0, 8u);

    /* VehicleSpeed */
    v = (uint64_t)src_p->vehicle_speed;
    dst_p[0] = (uint8_t)(dst_p[0] | (uint8_t)(v & 0xFFu));
    dst_p[1] = (uint8_t)(dst_p[1] | (uint8_t)((v >> 8) & 0xFFu));

    /* GearPosition */
    v = (uint64_t)src_p->gear_position;
    dst_p[2] = (uint8_t)(dst_p[2] | (uint8_t)(v & 0x7u));

    /* BrakePressed */
    v = (uint64_t)src_p->brake_pressed;
    dst_p[2] = (uint8_t)(dst_p[2] | (uint8_t)((v & 0x1u) << 3));

    /* DriveMode */
    v = (uint64_t)src_p->drive_mode;
    dst_p[2] = (uint8_t)(dst_p[2] | (uint8_t)((v & 0x3u) << 4));

    /* AcceleratorPedal */
    v = (uint64_t)src_p->accelerator_pedal;
    dst_p[3] = (uint8_t)(dst_p[3] | (uint8_t)(v & 0xFFu));

    /* SteeringAngle */
    v = (uint64_t)src_p->steering_angle;
    dst_p[4] = (uint8_t)(dst_p[4] | (uint8_t)(v & 0xFFu));
    dst_p[5] = (uint8_t)(dst_p[5] | (uint8_t)((v >> 8) & 0xFFu));

    /* RollingCounter */
    v = (uint64_t)src_p->rolling_counter;
    dst_p[7] = (uint8_t)(dst_p[7] | (uint8_t)(v & 0xFu));

    /* Checksum */
    v = (uint64_t)src_p->checksum;
    dst_p[7] = (uint8_t)(dst_p[7] | (uint8_t)((v & 0xFu) << 4));

    return 8;
}

int powertrain_vehicle_status_unpack(powertrain_vehicle_status_t *dst_p, const uint8_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 8u) {
        return -1;
    }

    (void)memset(dst_p, 0, sizeof(*dst_p));

    /* VehicleSpeed */
    v = 0u;
    v |= (uint64_t)src_p[0];
    v |= ((uint64_t)src_p[1] << 8);
    dst_p->vehicle_speed = (uint16_t)v;

    /* GearPosition */
    v = 0u;
    v |= ((uint64_t)src_p[2] & 0x7u);
    dst_p->gear_position = (uint8_t)v;

    /* BrakePressed */
    v = 0u;
    v |= (((uint64_t)src_p[2] >> 3) & 0x1u);
    dst_p->brake_pressed = (uint8_t)v;

    /* DriveMode */
    v = 0u;
    v |= (((uint64_t)src_p[2] >> 4) & 0x3u);
    dst_p->drive_mode = (uint8_t)v;

    /* AcceleratorPedal */
    v = 0u;
    v |= (uint64_t)src_p[3];
    dst_p->accelerator_pedal = (uint8_t)v;

    /* SteeringAngle */
    v = 0u;
    v |= (uint64_t)src_p[4];
    v |= ((uint64_t)src_p[5] << 8);
    if ((v & 0x8000ull) != 0ull) {
        v |= 0xFFFFFFFFFFFF0000ull;
    }
    dst_p->steering_angle = (int16_t)(int64_t)v;

    /* RollingCounter */
    v = 0u;
    v |= ((uint64_t)src_p[7] & 0xFu);
    dst_p->rolling_counter = (uint8_t)v;

    /* Checksum */
    v = 0u;
    v |= (((uint64_t)src_p[7] >> 4) & 0xFu);
    dst_p->checksum = (uint8_t)v;

    return 0;
}

double powertrain_vehicle_status_vehicle_speed_decode(uint16_t raw)
{
    return (double)raw * 0.01;
}

uint16_t powertrain_vehicle_status_vehicle_speed_encode(double value)
{
    double r = value / 0.01;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 65535.0) {
        r = 65535.0;
    }
    return (uint16_t)(r + 0.5);
}

bool powertrain_vehicle_status_vehicle_speed_is_in_range(uint16_t raw)
{
    (void)raw;
    return true;
}

double powertrain_vehicle_status_gear_position_decode(uint8_t raw)
{
    return (double)raw;
}

uint8_t powertrain_vehicle_status_gear_position_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 7.0) {
        r = 7.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_vehicle_status_gear_position_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 7ull);
}

double powertrain_vehicle_status_brake_pressed_decode(uint8_t raw)
{
    return (double)raw;
}

uint8_t powertrain_vehicle_status_brake_pressed_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 1.0) {
        r = 1.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_vehicle_status_brake_pressed_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 1ull);
}

double powertrain_vehicle_status_drive_mode_decode(uint8_t raw)
{
    return (double)raw;
}

uint8_t powertrain_vehicle_status_drive_mode_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 3.0) {
        r = 3.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_vehicle_status_drive_mode_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 3ull);
}

double powertrain_vehicle_status_accelerator_pedal_decode(uint8_t raw)
{
    return (double)raw * 0.4;
}

uint8_t powertrain_vehicle_status_accelerator_pedal_encode(double value)
{
    double r = value / 0.4;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 255.0) {
        r = 255.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_vehicle_status_accelerator_pedal_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 250ull);
}

double powertrain_vehicle_status_steering_angle_decode(int16_t raw)
{
    return (double)raw * 0.1;
}

int16_t powertrain_vehicle_status_steering_angle_encode(double value)
{
    double r = value / 0.1;

    if (!(r >= -32768.0)) {
        r = -32768.0;
    }
    if (r > 32767.0) {
        r = 32767.0;
    }
    return (int16_t)((r >= 0.0) ? (r + 0.5) : (r - 0.5));
}

bool powertrain_vehicle_status_steering_angle_is_in_range(int16_t raw)
{
    (void)raw;
    return true;
}

double powertrain_vehicle_status_rolling_counter_decode(uint8_t raw)
{
    return (double)raw;
}

uint8_t powertrain_vehicle_status_rolling_counter_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 15.0) {
        r = 15.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_vehicle_status_rolling_counter_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 15ull);
}

double powertrain_vehicle_status_checksum_decode(uint8_t raw)
{
    return (double)raw;
}

uint8_t powertrain_vehicle_status_checksum_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 15.0) {
        r = 15.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_vehicle_status_checksum_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 15ull);
}

void powertrain_battery_status_init(powertrain_battery_status_t *msg_p)
{
    (void)memset(msg_p, 0, sizeof(*msg_p));
}

int powertrain_battery_status_pack(uint8_t *dst_p, const powertrain_battery_status_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 8u) {
        return -1;
    }

    (void)memset(dst_p, 0, 8u);

    /* PackVoltage */
    v = (uint64_t)src_p->pack_voltage;
    dst_p[0] = (uint8_t)(dst_p[0] | (uint8_t)((v >> 8) & 0xFFu));
    dst_p[1] = (uint8_t)(dst_p[1] | (uint8_t)(v & 0xFFu));

    /* PackCurrent */
    v = (uint64_t)src_p->pack_current;
    dst_p[2] = (uint8_t)(dst_p[2] | (uint8_t)((v >> 8) & 0xFFu));
    dst_p[3] = (uint8_t)(dst_p[3] | (uint8_t)(v & 0xFFu));

    /* StateOfCharge */
    v = (uint64_t)src_p->state_of_charge;
    dst_p[4] = (uint8_t)(dst_p[4] | (uint8_t)(v & 0xFFu));

    /* MaxCellTemp */
    v = (uint64_t)src_p->max_cell_temp;
    dst_p[5] = (uint8_t)(dst_p[5] | (uint8_t)(v & 0xFFu));

    /* ContactorState */
    v = (uint64_t)src_p->contactor_state;
    dst_p[6] = (uint8_t)(dst_p[6] | (uint8_t)((v & 0x3u) << 6));

    /* BalancingActive */
    v = (uint64_t)src_p->balancing_active;
    dst_p[6] = (uint8_t)(dst_p[6] | (uint8_t)((v & 0x1u) << 5));

    /* CellCount */
    v = (uint64_t)src_p->cell_count;
    dst_p[6] = (uint8_t)(dst_p[6] | (uint8_t)(v & 0x1Fu));

    return 8;
}

int powertrain_battery_status_unpack(powertrain_battery_status_t *dst_p, const uint8_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 8u) {
        return -1;
    }

    (void)memset(dst_p, 0, sizeof(*dst_p));

    /* PackVoltage */
    v = 0u;
    v |= ((uint64_t)src_p[0] << 8);
    v |= (uint64_t)src_p[1];
    dst_p->pack_voltage = (uint16_t)v;

    /* PackCurrent */
    v = 0u;
    v |= ((uint64_t)src_p[2] << 8);
    v |= (uint64_t)src_p[3];
    if ((v & 0x8000ull) != 0ull) {
        v |= 0xFFFFFFFFFFFF0000ull;
    }
    dst_p->pack_current = (int16_t)(int64_t)v;

    /* StateOfCharge */
    v = 0u;
    v |= (uint64_t)src_p[4];
    dst_p->state_of_charge = (uint8_t)v;

    /* MaxCellTemp */
    v = 0u;
    v |= (uint64_t)src_p[5];
    if ((v & 0x80ull) != 0ull) {
        v |= 0xFFFFFFFFFFFFFF00ull;
    }
    dst_p->max_cell_temp = (int8_t)(int64_t)v;

    /* ContactorState */
    v = 0u;
    v |= (((uint64_t)src_p[6] >> 6) & 0x3u);
    dst_p->contactor_state = (uint8_t)v;

    /* BalancingActive */
    v = 0u;
    v |= (((uint64_t)src_p[6] >> 5) & 0x1u);
    dst_p->balancing_active = (uint8_t)v;

    /* CellCount */
    v = 0u;
    v |= ((uint64_t)src_p[6] & 0x1Fu);
    dst_p->cell_count = (uint8_t)v;

    return 0;
}

double powertrain_battery_status_pack_voltage_decode(uint16_t raw)
{
    return (double)raw * 0.01;
}

uint16_t powertrain_battery_status_pack_voltage_encode(double value)
{
    double r = value / 0.01;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 65535.0) {
        r = 65535.0;
    }
    return (uint16_t)(r + 0.5);
}

bool powertrain_battery_status_pack_voltage_is_in_range(uint16_t raw)
{
    (void)raw;
    return true;
}

double powertrain_battery_status_pack_current_decode(int16_t raw)
{
    return (double)raw * 0.05;
}

int16_t powertrain_battery_status_pack_current_encode(double value)
{
    double r = value / 0.05;

    if (!(r >= -32768.0)) {
        r = -32768.0;
    }
    if (r > 32767.0) {
        r = 32767.0;
    }
    return (int16_t)((r >= 0.0) ? (r + 0.5) : (r - 0.5));
}

bool powertrain_battery_status_pack_current_is_in_range(int16_t raw)
{
    (void)raw;
    return true;
}

double powertrain_battery_status_state_of_charge_decode(uint8_t raw)
{
    return (double)raw * 0.5;
}

uint8_t powertrain_battery_status_state_of_charge_encode(double value)
{
    double r = value / 0.5;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 255.0) {
        r = 255.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_battery_status_state_of_charge_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 200ull);
}

double powertrain_battery_status_max_cell_temp_decode(int8_t raw)
{
    return (double)raw;
}

int8_t powertrain_battery_status_max_cell_temp_encode(double value)
{
    double r = value;

    if (!(r >= -128.0)) {
        r = -128.0;
    }
    if (r > 127.0) {
        r = 127.0;
    }
    return (int8_t)((r >= 0.0) ? (r + 0.5) : (r - 0.5));
}

bool powertrain_battery_status_max_cell_temp_is_in_range(int8_t raw)
{
    return ((int64_t)raw >= -40LL) && ((int64_t)raw <= 85LL);
}

double powertrain_battery_status_contactor_state_decode(uint8_t raw)
{
    return (double)raw;
}

uint8_t powertrain_battery_status_contactor_state_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 3.0) {
        r = 3.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_battery_status_contactor_state_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 3ull);
}

double powertrain_battery_status_balancing_active_decode(uint8_t raw)
{
    return (double)raw;
}

uint8_t powertrain_battery_status_balancing_active_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 1.0) {
        r = 1.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_battery_status_balancing_active_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 1ull);
}

double powertrain_battery_status_cell_count_decode(uint8_t raw)
{
    return (double)raw;
}

uint8_t powertrain_battery_status_cell_count_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 31.0) {
        r = 31.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_battery_status_cell_count_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 31ull);
}

void powertrain_inverter_telemetry_init(powertrain_inverter_telemetry_t *msg_p)
{
    (void)memset(msg_p, 0, sizeof(*msg_p));
}

int powertrain_inverter_telemetry_pack(uint8_t *dst_p, const powertrain_inverter_telemetry_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 8u) {
        return -1;
    }

    (void)memset(dst_p, 0, 8u);

    /* PageIndex */
    v = (uint64_t)src_p->page_index;
    dst_p[0] = (uint8_t)(dst_p[0] | (uint8_t)(v & 0xFFu));

    /* InverterState */
    v = (uint64_t)src_p->inverter_state;
    dst_p[7] = (uint8_t)(dst_p[7] | (uint8_t)(v & 0x7u));

    switch (src_p->page_index) {
    case 0:
        /* MotorSpeed */
        v = (uint64_t)src_p->motor_speed;
        dst_p[1] = (uint8_t)(dst_p[1] | (uint8_t)(v & 0xFFu));
        dst_p[2] = (uint8_t)(dst_p[2] | (uint8_t)((v >> 8) & 0xFFu));

        /* MotorTorque */
        v = (uint64_t)src_p->motor_torque;
        dst_p[3] = (uint8_t)(dst_p[3] | (uint8_t)(v & 0xFFu));
        dst_p[4] = (uint8_t)(dst_p[4] | (uint8_t)((v >> 8) & 0xFFu));
        break;
    case 1:
        /* StatorTemp */
        v = (uint64_t)src_p->stator_temp;
        dst_p[1] = (uint8_t)(dst_p[1] | (uint8_t)(v & 0xFFu));

        /* IgbtTemp */
        v = (uint64_t)src_p->igbt_temp;
        dst_p[2] = (uint8_t)(dst_p[2] | (uint8_t)(v & 0xFFu));
        break;
    case 2:
        /* DcLinkVoltage */
        v = (uint64_t)src_p->dc_link_voltage;
        dst_p[1] = (uint8_t)(dst_p[1] | (uint8_t)(v & 0xFFu));
        dst_p[2] = (uint8_t)(dst_p[2] | (uint8_t)((v >> 8) & 0xFFu));

        /* FaultCode */
        v = (uint64_t)src_p->fault_code;
        dst_p[3] = (uint8_t)(dst_p[3] | (uint8_t)(v & 0xFFu));
        dst_p[4] = (uint8_t)(dst_p[4] | (uint8_t)((v >> 8) & 0xFFu));
        break;
    default:
        break;
    }

    return 8;
}

int powertrain_inverter_telemetry_unpack(powertrain_inverter_telemetry_t *dst_p, const uint8_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 8u) {
        return -1;
    }

    (void)memset(dst_p, 0, sizeof(*dst_p));

    /* PageIndex */
    v = 0u;
    v |= (uint64_t)src_p[0];
    dst_p->page_index = (uint8_t)v;

    /* InverterState */
    v = 0u;
    v |= ((uint64_t)src_p[7] & 0x7u);
    dst_p->inverter_state = (uint8_t)v;

    switch (dst_p->page_index) {
    case 0:
        /* MotorSpeed */
        v = 0u;
        v |= (uint64_t)src_p[1];
        v |= ((uint64_t)src_p[2] << 8);
        if ((v & 0x8000ull) != 0ull) {
            v |= 0xFFFFFFFFFFFF0000ull;
        }
        dst_p->motor_speed = (int16_t)(int64_t)v;

        /* MotorTorque */
        v = 0u;
        v |= (uint64_t)src_p[3];
        v |= ((uint64_t)src_p[4] << 8);
        if ((v & 0x8000ull) != 0ull) {
            v |= 0xFFFFFFFFFFFF0000ull;
        }
        dst_p->motor_torque = (int16_t)(int64_t)v;
        break;
    case 1:
        /* StatorTemp */
        v = 0u;
        v |= (uint64_t)src_p[1];
        dst_p->stator_temp = (uint8_t)v;

        /* IgbtTemp */
        v = 0u;
        v |= (uint64_t)src_p[2];
        dst_p->igbt_temp = (uint8_t)v;
        break;
    case 2:
        /* DcLinkVoltage */
        v = 0u;
        v |= (uint64_t)src_p[1];
        v |= ((uint64_t)src_p[2] << 8);
        dst_p->dc_link_voltage = (uint16_t)v;

        /* FaultCode */
        v = 0u;
        v |= (uint64_t)src_p[3];
        v |= ((uint64_t)src_p[4] << 8);
        dst_p->fault_code = (uint16_t)v;
        break;
    default:
        break;
    }

    return 0;
}

double powertrain_inverter_telemetry_page_index_decode(uint8_t raw)
{
    return (double)raw;
}

uint8_t powertrain_inverter_telemetry_page_index_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 255.0) {
        r = 255.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_inverter_telemetry_page_index_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 2ull);
}

double powertrain_inverter_telemetry_motor_speed_decode(int16_t raw)
{
    return (double)raw;
}

int16_t powertrain_inverter_telemetry_motor_speed_encode(double value)
{
    double r = value;

    if (!(r >= -32768.0)) {
        r = -32768.0;
    }
    if (r > 32767.0) {
        r = 32767.0;
    }
    return (int16_t)((r >= 0.0) ? (r + 0.5) : (r - 0.5));
}

bool powertrain_inverter_telemetry_motor_speed_is_in_range(int16_t raw)
{
    return ((int64_t)raw >= -20000LL) && ((int64_t)raw <= 20000LL);
}

double powertrain_inverter_telemetry_motor_torque_decode(int16_t raw)
{
    return (double)raw * 0.1;
}

int16_t powertrain_inverter_telemetry_motor_torque_encode(double value)
{
    double r = value / 0.1;

    if (!(r >= -32768.0)) {
        r = -32768.0;
    }
    if (r > 32767.0) {
        r = 32767.0;
    }
    return (int16_t)((r >= 0.0) ? (r + 0.5) : (r - 0.5));
}

bool powertrain_inverter_telemetry_motor_torque_is_in_range(int16_t raw)
{
    return ((int64_t)raw >= -5000LL) && ((int64_t)raw <= 5000LL);
}

double powertrain_inverter_telemetry_stator_temp_decode(uint8_t raw)
{
    return (double)raw - 40.0;
}

uint8_t powertrain_inverter_telemetry_stator_temp_encode(double value)
{
    double r = (value + 40.0);

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 255.0) {
        r = 255.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_inverter_telemetry_stator_temp_is_in_range(uint8_t raw)
{
    (void)raw;
    return true;
}

double powertrain_inverter_telemetry_igbt_temp_decode(uint8_t raw)
{
    return (double)raw - 40.0;
}

uint8_t powertrain_inverter_telemetry_igbt_temp_encode(double value)
{
    double r = (value + 40.0);

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 255.0) {
        r = 255.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_inverter_telemetry_igbt_temp_is_in_range(uint8_t raw)
{
    (void)raw;
    return true;
}

double powertrain_inverter_telemetry_dc_link_voltage_decode(uint16_t raw)
{
    return (double)raw * 0.1;
}

uint16_t powertrain_inverter_telemetry_dc_link_voltage_encode(double value)
{
    double r = value / 0.1;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 65535.0) {
        r = 65535.0;
    }
    return (uint16_t)(r + 0.5);
}

bool powertrain_inverter_telemetry_dc_link_voltage_is_in_range(uint16_t raw)
{
    return ((uint64_t)raw <= 10000ull);
}

double powertrain_inverter_telemetry_fault_code_decode(uint16_t raw)
{
    return (double)raw;
}

uint16_t powertrain_inverter_telemetry_fault_code_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 65535.0) {
        r = 65535.0;
    }
    return (uint16_t)(r + 0.5);
}

bool powertrain_inverter_telemetry_fault_code_is_in_range(uint16_t raw)
{
    (void)raw;
    return true;
}

double powertrain_inverter_telemetry_inverter_state_decode(uint8_t raw)
{
    return (double)raw;
}

uint8_t powertrain_inverter_telemetry_inverter_state_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 7.0) {
        r = 7.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_inverter_telemetry_inverter_state_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 7ull);
}

void powertrain_charger_limits_init(powertrain_charger_limits_t *msg_p)
{
    (void)memset(msg_p, 0, sizeof(*msg_p));
}

int powertrain_charger_limits_pack(uint8_t *dst_p, const powertrain_charger_limits_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 8u) {
        return -1;
    }

    (void)memset(dst_p, 0, 8u);

    /* ChargeCurrentLimit */
    v = (uint64_t)src_p->charge_current_limit;
    dst_p[0] = (uint8_t)(dst_p[0] | (uint8_t)(v & 0xFFu));
    dst_p[1] = (uint8_t)(dst_p[1] | (uint8_t)((v >> 8) & 0xFFu));

    /* ChargeVoltageLimit */
    v = (uint64_t)src_p->charge_voltage_limit;
    dst_p[2] = (uint8_t)(dst_p[2] | (uint8_t)(v & 0xFFu));
    dst_p[3] = (uint8_t)(dst_p[3] | (uint8_t)((v >> 8) & 0xFFu));

    /* ChargerEnable */
    v = (uint64_t)src_p->charger_enable;
    dst_p[4] = (uint8_t)(dst_p[4] | (uint8_t)(v & 0x1u));

    return 8;
}

int powertrain_charger_limits_unpack(powertrain_charger_limits_t *dst_p, const uint8_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 8u) {
        return -1;
    }

    (void)memset(dst_p, 0, sizeof(*dst_p));

    /* ChargeCurrentLimit */
    v = 0u;
    v |= (uint64_t)src_p[0];
    v |= ((uint64_t)src_p[1] << 8);
    dst_p->charge_current_limit = (uint16_t)v;

    /* ChargeVoltageLimit */
    v = 0u;
    v |= (uint64_t)src_p[2];
    v |= ((uint64_t)src_p[3] << 8);
    dst_p->charge_voltage_limit = (uint16_t)v;

    /* ChargerEnable */
    v = 0u;
    v |= ((uint64_t)src_p[4] & 0x1u);
    dst_p->charger_enable = (uint8_t)v;

    return 0;
}

double powertrain_charger_limits_charge_current_limit_decode(uint16_t raw)
{
    return (double)raw * 0.1;
}

uint16_t powertrain_charger_limits_charge_current_limit_encode(double value)
{
    double r = value / 0.1;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 65535.0) {
        r = 65535.0;
    }
    return (uint16_t)(r + 0.5);
}

bool powertrain_charger_limits_charge_current_limit_is_in_range(uint16_t raw)
{
    (void)raw;
    return true;
}

double powertrain_charger_limits_charge_voltage_limit_decode(uint16_t raw)
{
    return (double)raw * 0.1;
}

uint16_t powertrain_charger_limits_charge_voltage_limit_encode(double value)
{
    double r = value / 0.1;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 65535.0) {
        r = 65535.0;
    }
    return (uint16_t)(r + 0.5);
}

bool powertrain_charger_limits_charge_voltage_limit_is_in_range(uint16_t raw)
{
    (void)raw;
    return true;
}

double powertrain_charger_limits_charger_enable_decode(uint8_t raw)
{
    return (double)raw;
}

uint8_t powertrain_charger_limits_charger_enable_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 1.0) {
        r = 1.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_charger_limits_charger_enable_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 1ull);
}

void powertrain_thermal_sensors_init(powertrain_thermal_sensors_t *msg_p)
{
    (void)memset(msg_p, 0, sizeof(*msg_p));
}

int powertrain_thermal_sensors_pack(uint8_t *dst_p, const powertrain_thermal_sensors_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 8u) {
        return -1;
    }

    (void)memset(dst_p, 0, 8u);

    /* CoolantFlow */
    v = (uint64_t)src_p->coolant_flow;
    dst_p[0] = (uint8_t)(dst_p[0] | (uint8_t)(v & 0xFFu));
    dst_p[1] = (uint8_t)(dst_p[1] | (uint8_t)((v >> 8) & 0xFFu));
    dst_p[2] = (uint8_t)(dst_p[2] | (uint8_t)((v >> 16) & 0xFFu));
    dst_p[3] = (uint8_t)(dst_p[3] | (uint8_t)((v >> 24) & 0xFFu));

    /* AmbientTemp */
    v = (uint64_t)src_p->ambient_temp;
    dst_p[4] = (uint8_t)(dst_p[4] | (uint8_t)(v & 0xFFu));
    dst_p[5] = (uint8_t)(dst_p[5] | (uint8_t)((v >> 8) & 0xFFu));
    dst_p[6] = (uint8_t)(dst_p[6] | (uint8_t)((v >> 16) & 0xFFu));
    dst_p[7] = (uint8_t)(dst_p[7] | (uint8_t)((v >> 24) & 0xFFu));

    return 8;
}

int powertrain_thermal_sensors_unpack(powertrain_thermal_sensors_t *dst_p, const uint8_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 8u) {
        return -1;
    }

    (void)memset(dst_p, 0, sizeof(*dst_p));

    /* CoolantFlow */
    v = 0u;
    v |= (uint64_t)src_p[0];
    v |= ((uint64_t)src_p[1] << 8);
    v |= ((uint64_t)src_p[2] << 16);
    v |= ((uint64_t)src_p[3] << 24);
    dst_p->coolant_flow = (uint32_t)v;

    /* AmbientTemp */
    v = 0u;
    v |= (uint64_t)src_p[4];
    v |= ((uint64_t)src_p[5] << 8);
    v |= ((uint64_t)src_p[6] << 16);
    v |= ((uint64_t)src_p[7] << 24);
    dst_p->ambient_temp = (uint32_t)v;

    return 0;
}

double powertrain_thermal_sensors_coolant_flow_decode(uint32_t raw)
{
    float f;

    (void)memcpy(&f, &raw, sizeof(f));
    return (double)f;
}

uint32_t powertrain_thermal_sensors_coolant_flow_encode(double value)
{
    double r = value;
    float f;
    uint32_t raw;

    if (r > (double)FLT_MAX) {
        r = (double)FLT_MAX;
    }
    if (r < -(double)FLT_MAX) {
        r = -(double)FLT_MAX;
    }
    f = (float)r;
    (void)memcpy(&raw, &f, sizeof(raw));
    return raw;
}

bool powertrain_thermal_sensors_coolant_flow_is_in_range(uint32_t raw)
{
    double value = powertrain_thermal_sensors_coolant_flow_decode(raw);

    return (value >= 0.0) && (value <= 100.0);
}

double powertrain_thermal_sensors_ambient_temp_decode(uint32_t raw)
{
    float f;

    (void)memcpy(&f, &raw, sizeof(f));
    return (double)f;
}

uint32_t powertrain_thermal_sensors_ambient_temp_encode(double value)
{
    double r = value;
    float f;
    uint32_t raw;

    if (r > (double)FLT_MAX) {
        r = (double)FLT_MAX;
    }
    if (r < -(double)FLT_MAX) {
        r = -(double)FLT_MAX;
    }
    f = (float)r;
    (void)memcpy(&raw, &f, sizeof(raw));
    return raw;
}

bool powertrain_thermal_sensors_ambient_temp_is_in_range(uint32_t raw)
{
    double value = powertrain_thermal_sensors_ambient_temp_decode(raw);

    return (value >= -50.0) && (value <= 80.0);
}

void powertrain_wheel_speeds_init(powertrain_wheel_speeds_t *msg_p)
{
    (void)memset(msg_p, 0, sizeof(*msg_p));
}

int powertrain_wheel_speeds_pack(uint8_t *dst_p, const powertrain_wheel_speeds_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 8u) {
        return -1;
    }

    (void)memset(dst_p, 0, 8u);

    /* WheelSpeedFL */
    v = (uint64_t)src_p->wheel_speed_fl;
    dst_p[0] = (uint8_t)(dst_p[0] | (uint8_t)((v >> 4) & 0xFFu));
    dst_p[1] = (uint8_t)(dst_p[1] | (uint8_t)((v & 0xFu) << 4));

    /* WheelSpeedFR */
    v = (uint64_t)src_p->wheel_speed_fr;
    dst_p[1] = (uint8_t)(dst_p[1] | (uint8_t)((v >> 8) & 0xFu));
    dst_p[2] = (uint8_t)(dst_p[2] | (uint8_t)(v & 0xFFu));

    /* WheelSpeedRL */
    v = (uint64_t)src_p->wheel_speed_rl;
    dst_p[3] = (uint8_t)(dst_p[3] | (uint8_t)((v >> 4) & 0xFFu));
    dst_p[4] = (uint8_t)(dst_p[4] | (uint8_t)((v & 0xFu) << 4));

    /* WheelSpeedRR */
    v = (uint64_t)src_p->wheel_speed_rr;
    dst_p[4] = (uint8_t)(dst_p[4] | (uint8_t)((v >> 8) & 0xFu));
    dst_p[5] = (uint8_t)(dst_p[5] | (uint8_t)(v & 0xFFu));

    /* YawRate */
    v = (uint64_t)src_p->yaw_rate;
    dst_p[6] = (uint8_t)(dst_p[6] | (uint8_t)(v & 0xFFu));
    dst_p[7] = (uint8_t)(dst_p[7] | (uint8_t)((v >> 8) & 0x3Fu));

    /* WheelSpeedValid */
    v = (uint64_t)src_p->wheel_speed_valid;
    dst_p[7] = (uint8_t)(dst_p[7] | (uint8_t)((v & 0x3u) << 6));

    return 8;
}

int powertrain_wheel_speeds_unpack(powertrain_wheel_speeds_t *dst_p, const uint8_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 8u) {
        return -1;
    }

    (void)memset(dst_p, 0, sizeof(*dst_p));

    /* WheelSpeedFL */
    v = 0u;
    v |= ((uint64_t)src_p[0] << 4);
    v |= (((uint64_t)src_p[1] >> 4) & 0xFu);
    dst_p->wheel_speed_fl = (uint16_t)v;

    /* WheelSpeedFR */
    v = 0u;
    v |= (((uint64_t)src_p[1] & 0xFu) << 8);
    v |= (uint64_t)src_p[2];
    dst_p->wheel_speed_fr = (uint16_t)v;

    /* WheelSpeedRL */
    v = 0u;
    v |= ((uint64_t)src_p[3] << 4);
    v |= (((uint64_t)src_p[4] >> 4) & 0xFu);
    dst_p->wheel_speed_rl = (uint16_t)v;

    /* WheelSpeedRR */
    v = 0u;
    v |= (((uint64_t)src_p[4] & 0xFu) << 8);
    v |= (uint64_t)src_p[5];
    dst_p->wheel_speed_rr = (uint16_t)v;

    /* YawRate */
    v = 0u;
    v |= (uint64_t)src_p[6];
    v |= (((uint64_t)src_p[7] & 0x3Fu) << 8);
    if ((v & 0x2000ull) != 0ull) {
        v |= 0xFFFFFFFFFFFFC000ull;
    }
    dst_p->yaw_rate = (int16_t)(int64_t)v;

    /* WheelSpeedValid */
    v = 0u;
    v |= (((uint64_t)src_p[7] >> 6) & 0x3u);
    dst_p->wheel_speed_valid = (uint8_t)v;

    return 0;
}

double powertrain_wheel_speeds_wheel_speed_fl_decode(uint16_t raw)
{
    return (double)raw * 0.1;
}

uint16_t powertrain_wheel_speeds_wheel_speed_fl_encode(double value)
{
    double r = value / 0.1;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 4095.0) {
        r = 4095.0;
    }
    return (uint16_t)(r + 0.5);
}

bool powertrain_wheel_speeds_wheel_speed_fl_is_in_range(uint16_t raw)
{
    return ((uint64_t)raw <= 4095ull);
}

double powertrain_wheel_speeds_wheel_speed_fr_decode(uint16_t raw)
{
    return (double)raw * 0.1;
}

uint16_t powertrain_wheel_speeds_wheel_speed_fr_encode(double value)
{
    double r = value / 0.1;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 4095.0) {
        r = 4095.0;
    }
    return (uint16_t)(r + 0.5);
}

bool powertrain_wheel_speeds_wheel_speed_fr_is_in_range(uint16_t raw)
{
    return ((uint64_t)raw <= 4095ull);
}

double powertrain_wheel_speeds_wheel_speed_rl_decode(uint16_t raw)
{
    return (double)raw * 0.1;
}

uint16_t powertrain_wheel_speeds_wheel_speed_rl_encode(double value)
{
    double r = value / 0.1;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 4095.0) {
        r = 4095.0;
    }
    return (uint16_t)(r + 0.5);
}

bool powertrain_wheel_speeds_wheel_speed_rl_is_in_range(uint16_t raw)
{
    return ((uint64_t)raw <= 4095ull);
}

double powertrain_wheel_speeds_wheel_speed_rr_decode(uint16_t raw)
{
    return (double)raw * 0.1;
}

uint16_t powertrain_wheel_speeds_wheel_speed_rr_encode(double value)
{
    double r = value / 0.1;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 4095.0) {
        r = 4095.0;
    }
    return (uint16_t)(r + 0.5);
}

bool powertrain_wheel_speeds_wheel_speed_rr_is_in_range(uint16_t raw)
{
    return ((uint64_t)raw <= 4095ull);
}

double powertrain_wheel_speeds_yaw_rate_decode(int16_t raw)
{
    return (double)raw * 0.01;
}

int16_t powertrain_wheel_speeds_yaw_rate_encode(double value)
{
    double r = value / 0.01;

    if (!(r >= -8192.0)) {
        r = -8192.0;
    }
    if (r > 8191.0) {
        r = 8191.0;
    }
    return (int16_t)((r >= 0.0) ? (r + 0.5) : (r - 0.5));
}

bool powertrain_wheel_speeds_yaw_rate_is_in_range(int16_t raw)
{
    return ((int64_t)raw >= -8192LL) && ((int64_t)raw <= 8191LL);
}

double powertrain_wheel_speeds_wheel_speed_valid_decode(uint8_t raw)
{
    return (double)raw;
}

uint8_t powertrain_wheel_speeds_wheel_speed_valid_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 3.0) {
        r = 3.0;
    }
    return (uint8_t)(r + 0.5);
}

bool powertrain_wheel_speeds_wheel_speed_valid_is_in_range(uint8_t raw)
{
    return ((uint64_t)raw <= 3ull);
}

void powertrain_diagnostic_fd_init(powertrain_diagnostic_fd_t *msg_p)
{
    (void)memset(msg_p, 0, sizeof(*msg_p));
}

int powertrain_diagnostic_fd_pack(uint8_t *dst_p, const powertrain_diagnostic_fd_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 64u) {
        return -1;
    }

    (void)memset(dst_p, 0, 64u);

    /* Odometer */
    v = (uint64_t)src_p->odometer;
    dst_p[0] = (uint8_t)(dst_p[0] | (uint8_t)(v & 0xFFu));
    dst_p[1] = (uint8_t)(dst_p[1] | (uint8_t)((v >> 8) & 0xFFu));
    dst_p[2] = (uint8_t)(dst_p[2] | (uint8_t)((v >> 16) & 0xFFu));
    dst_p[3] = (uint8_t)(dst_p[3] | (uint8_t)((v >> 24) & 0xFFu));

    /* TripId */
    v = (uint64_t)src_p->trip_id;
    dst_p[4] = (uint8_t)(dst_p[4] | (uint8_t)(v & 0xFFu));
    dst_p[5] = (uint8_t)(dst_p[5] | (uint8_t)((v >> 8) & 0xFFu));
    dst_p[6] = (uint8_t)(dst_p[6] | (uint8_t)((v >> 16) & 0xFFu));
    dst_p[7] = (uint8_t)(dst_p[7] | (uint8_t)((v >> 24) & 0xFFu));

    /* SerialNumber */
    v = (uint64_t)src_p->serial_number;
    dst_p[8] = (uint8_t)(dst_p[8] | (uint8_t)(v & 0xFFu));
    dst_p[9] = (uint8_t)(dst_p[9] | (uint8_t)((v >> 8) & 0xFFu));
    dst_p[10] = (uint8_t)(dst_p[10] | (uint8_t)((v >> 16) & 0xFFu));
    dst_p[11] = (uint8_t)(dst_p[11] | (uint8_t)((v >> 24) & 0xFFu));
    dst_p[12] = (uint8_t)(dst_p[12] | (uint8_t)((v >> 32) & 0xFFu));
    dst_p[13] = (uint8_t)(dst_p[13] | (uint8_t)((v >> 40) & 0xFFu));
    dst_p[14] = (uint8_t)(dst_p[14] | (uint8_t)((v >> 48) & 0xFFu));
    dst_p[15] = (uint8_t)(dst_p[15] | (uint8_t)((v >> 56) & 0xFFu));

    /* FirmwareCrc */
    v = (uint64_t)src_p->firmware_crc;
    dst_p[16] = (uint8_t)(dst_p[16] | (uint8_t)(v & 0xFFu));
    dst_p[17] = (uint8_t)(dst_p[17] | (uint8_t)((v >> 8) & 0xFFu));
    dst_p[18] = (uint8_t)(dst_p[18] | (uint8_t)((v >> 16) & 0xFFu));
    dst_p[19] = (uint8_t)(dst_p[19] | (uint8_t)((v >> 24) & 0xFFu));

    /* LifetimeEnergy */
    v = (uint64_t)src_p->lifetime_energy;
    dst_p[23] = (uint8_t)(dst_p[23] | (uint8_t)((v >> 40) & 0xFFu));
    dst_p[24] = (uint8_t)(dst_p[24] | (uint8_t)((v >> 32) & 0xFFu));
    dst_p[25] = (uint8_t)(dst_p[25] | (uint8_t)((v >> 24) & 0xFFu));
    dst_p[26] = (uint8_t)(dst_p[26] | (uint8_t)((v >> 16) & 0xFFu));
    dst_p[27] = (uint8_t)(dst_p[27] | (uint8_t)((v >> 8) & 0xFFu));
    dst_p[28] = (uint8_t)(dst_p[28] | (uint8_t)(v & 0xFFu));

    /* TimestampNs */
    v = (uint64_t)src_p->timestamp_ns;
    dst_p[32] = (uint8_t)(dst_p[32] | (uint8_t)(v & 0xFFu));
    dst_p[33] = (uint8_t)(dst_p[33] | (uint8_t)((v >> 8) & 0xFFu));
    dst_p[34] = (uint8_t)(dst_p[34] | (uint8_t)((v >> 16) & 0xFFu));
    dst_p[35] = (uint8_t)(dst_p[35] | (uint8_t)((v >> 24) & 0xFFu));
    dst_p[36] = (uint8_t)(dst_p[36] | (uint8_t)((v >> 32) & 0xFFu));
    dst_p[37] = (uint8_t)(dst_p[37] | (uint8_t)((v >> 40) & 0xFFu));
    dst_p[38] = (uint8_t)(dst_p[38] | (uint8_t)((v >> 48) & 0xFFu));
    dst_p[39] = (uint8_t)(dst_p[39] | (uint8_t)((v >> 56) & 0xFFu));

    return 64;
}

int powertrain_diagnostic_fd_unpack(powertrain_diagnostic_fd_t *dst_p, const uint8_t *src_p, size_t size)
{
    uint64_t v;

    if (size < 64u) {
        return -1;
    }

    (void)memset(dst_p, 0, sizeof(*dst_p));

    /* Odometer */
    v = 0u;
    v |= (uint64_t)src_p[0];
    v |= ((uint64_t)src_p[1] << 8);
    v |= ((uint64_t)src_p[2] << 16);
    v |= ((uint64_t)src_p[3] << 24);
    dst_p->odometer = (uint32_t)v;

    /* TripId */
    v = 0u;
    v |= (uint64_t)src_p[4];
    v |= ((uint64_t)src_p[5] << 8);
    v |= ((uint64_t)src_p[6] << 16);
    v |= ((uint64_t)src_p[7] << 24);
    dst_p->trip_id = (uint32_t)v;

    /* SerialNumber */
    v = 0u;
    v |= (uint64_t)src_p[8];
    v |= ((uint64_t)src_p[9] << 8);
    v |= ((uint64_t)src_p[10] << 16);
    v |= ((uint64_t)src_p[11] << 24);
    v |= ((uint64_t)src_p[12] << 32);
    v |= ((uint64_t)src_p[13] << 40);
    v |= ((uint64_t)src_p[14] << 48);
    v |= ((uint64_t)src_p[15] << 56);
    dst_p->serial_number = (uint64_t)v;

    /* FirmwareCrc */
    v = 0u;
    v |= (uint64_t)src_p[16];
    v |= ((uint64_t)src_p[17] << 8);
    v |= ((uint64_t)src_p[18] << 16);
    v |= ((uint64_t)src_p[19] << 24);
    dst_p->firmware_crc = (uint32_t)v;

    /* LifetimeEnergy */
    v = 0u;
    v |= ((uint64_t)src_p[23] << 40);
    v |= ((uint64_t)src_p[24] << 32);
    v |= ((uint64_t)src_p[25] << 24);
    v |= ((uint64_t)src_p[26] << 16);
    v |= ((uint64_t)src_p[27] << 8);
    v |= (uint64_t)src_p[28];
    dst_p->lifetime_energy = (uint64_t)v;

    /* TimestampNs */
    v = 0u;
    v |= (uint64_t)src_p[32];
    v |= ((uint64_t)src_p[33] << 8);
    v |= ((uint64_t)src_p[34] << 16);
    v |= ((uint64_t)src_p[35] << 24);
    v |= ((uint64_t)src_p[36] << 32);
    v |= ((uint64_t)src_p[37] << 40);
    v |= ((uint64_t)src_p[38] << 48);
    v |= ((uint64_t)src_p[39] << 56);
    dst_p->timestamp_ns = (int64_t)(int64_t)v;

    return 0;
}

double powertrain_diagnostic_fd_odometer_decode(uint32_t raw)
{
    return (double)raw * 0.1;
}

uint32_t powertrain_diagnostic_fd_odometer_encode(double value)
{
    double r = value / 0.1;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 4294967295.0) {
        r = 4294967295.0;
    }
    return (uint32_t)(r + 0.5);
}

bool powertrain_diagnostic_fd_odometer_is_in_range(uint32_t raw)
{
    (void)raw;
    return true;
}

double powertrain_diagnostic_fd_trip_id_decode(uint32_t raw)
{
    return (double)raw;
}

uint32_t powertrain_diagnostic_fd_trip_id_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 4294967295.0) {
        r = 4294967295.0;
    }
    return (uint32_t)(r + 0.5);
}

bool powertrain_diagnostic_fd_trip_id_is_in_range(uint32_t raw)
{
    (void)raw;
    return true;
}

double powertrain_diagnostic_fd_serial_number_decode(uint64_t raw)
{
    return (double)raw;
}

uint64_t powertrain_diagnostic_fd_serial_number_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 18446744073709550000.0) {
        r = 18446744073709550000.0;
    }
    return (uint64_t)(r + 0.5);
}

bool powertrain_diagnostic_fd_serial_number_is_in_range(uint64_t raw)
{
    (void)raw;
    return true;
}

double powertrain_diagnostic_fd_firmware_crc_decode(uint32_t raw)
{
    return (double)raw;
}

uint32_t powertrain_diagnostic_fd_firmware_crc_encode(double value)
{
    double r = value;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 4294967295.0) {
        r = 4294967295.0;
    }
    return (uint32_t)(r + 0.5);
}

bool powertrain_diagnostic_fd_firmware_crc_is_in_range(uint32_t raw)
{
    (void)raw;
    return true;
}

double powertrain_diagnostic_fd_lifetime_energy_decode(uint64_t raw)
{
    return (double)raw * 0.001;
}

uint64_t powertrain_diagnostic_fd_lifetime_energy_encode(double value)
{
    double r = value / 0.001;

    if (!(r >= 0.0)) {
        r = 0.0;
    }
    if (r > 281474976710655.0) {
        r = 281474976710655.0;
    }
    return (uint64_t)(r + 0.5);
}

bool powertrain_diagnostic_fd_lifetime_energy_is_in_range(uint64_t raw)
{
    (void)raw;
    return true;
}

double powertrain_diagnostic_fd_timestamp_ns_decode(int64_t raw)
{
    return (double)raw;
}

int64_t powertrain_diagnostic_fd_timestamp_ns_encode(double value)
{
    double r = value;

    if (!(r >= -9223372036854776000.0)) {
        r = -9223372036854776000.0;
    }
    if (r > 9223372036854775000.0) {
        r = 9223372036854775000.0;
    }
    return (int64_t)((r >= 0.0) ? (r + 0.5) : (r - 0.5));
}

bool powertrain_diagnostic_fd_timestamp_ns_is_in_range(int64_t raw)
{
    (void)raw;
    return true;
}
