/**
 * powertrain.h
 *
 * Generated by canforge 0.1.0 from powertrain.dbc. Do not edit.
 * https://github.com/Swaraj-Patil/canforge
 *
 * Each message has a struct of raw signal values and pack/unpack functions
 * that convert it to and from the bytes on the wire. Each signal has
 * decode/encode helpers for physical values and a range check.
 * No heap allocation, no global state, C99.
 */

#ifndef POWERTRAIN_H
#define POWERTRAIN_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Frame IDs, lengths and formats. */
#define POWERTRAIN_VEHICLE_STATUS_FRAME_ID (0x100u)
#define POWERTRAIN_VEHICLE_STATUS_LENGTH (8u)
#define POWERTRAIN_VEHICLE_STATUS_IS_EXTENDED (0)
#define POWERTRAIN_BATTERY_STATUS_FRAME_ID (0x200u)
#define POWERTRAIN_BATTERY_STATUS_LENGTH (8u)
#define POWERTRAIN_BATTERY_STATUS_IS_EXTENDED (0)
#define POWERTRAIN_INVERTER_TELEMETRY_FRAME_ID (0x300u)
#define POWERTRAIN_INVERTER_TELEMETRY_LENGTH (8u)
#define POWERTRAIN_INVERTER_TELEMETRY_IS_EXTENDED (0)
#define POWERTRAIN_CHARGER_LIMITS_FRAME_ID (0x18FF50E5u)
#define POWERTRAIN_CHARGER_LIMITS_LENGTH (8u)
#define POWERTRAIN_CHARGER_LIMITS_IS_EXTENDED (1)
#define POWERTRAIN_THERMAL_SENSORS_FRAME_ID (0x400u)
#define POWERTRAIN_THERMAL_SENSORS_LENGTH (8u)
#define POWERTRAIN_THERMAL_SENSORS_IS_EXTENDED (0)
#define POWERTRAIN_WHEEL_SPEEDS_FRAME_ID (0x600u)
#define POWERTRAIN_WHEEL_SPEEDS_LENGTH (8u)
#define POWERTRAIN_WHEEL_SPEEDS_IS_EXTENDED (0)
#define POWERTRAIN_DIAGNOSTIC_FD_FRAME_ID (0x500u)
#define POWERTRAIN_DIAGNOSTIC_FD_LENGTH (64u)
#define POWERTRAIN_DIAGNOSTIC_FD_IS_EXTENDED (0)

/* Value descriptions. */
#define POWERTRAIN_VEHICLE_STATUS_GEAR_POSITION_PARK_CHOICE (0u)
#define POWERTRAIN_VEHICLE_STATUS_GEAR_POSITION_REVERSE_CHOICE (1u)
#define POWERTRAIN_VEHICLE_STATUS_GEAR_POSITION_NEUTRAL_CHOICE (2u)
#define POWERTRAIN_VEHICLE_STATUS_GEAR_POSITION_DRIVE_CHOICE (3u)
#define POWERTRAIN_VEHICLE_STATUS_GEAR_POSITION_INVALID_CHOICE (7u)
#define POWERTRAIN_VEHICLE_STATUS_DRIVE_MODE_ECO_CHOICE (0u)
#define POWERTRAIN_VEHICLE_STATUS_DRIVE_MODE_NORMAL_CHOICE (1u)
#define POWERTRAIN_VEHICLE_STATUS_DRIVE_MODE_SPORT_CHOICE (2u)
#define POWERTRAIN_VEHICLE_STATUS_DRIVE_MODE_TRACK_CHOICE (3u)
#define POWERTRAIN_BATTERY_STATUS_CONTACTOR_STATE_OPEN_CHOICE (0u)
#define POWERTRAIN_BATTERY_STATUS_CONTACTOR_STATE_PRECHARGE_CHOICE (1u)
#define POWERTRAIN_BATTERY_STATUS_CONTACTOR_STATE_CLOSED_CHOICE (2u)
#define POWERTRAIN_BATTERY_STATUS_CONTACTOR_STATE_FAULT_CHOICE (3u)
#define POWERTRAIN_INVERTER_TELEMETRY_PAGE_INDEX_SPEED_AND_TORQUE_CHOICE (0u)
#define POWERTRAIN_INVERTER_TELEMETRY_PAGE_INDEX_TEMPERATURES_CHOICE (1u)
#define POWERTRAIN_INVERTER_TELEMETRY_PAGE_INDEX_DC_LINK_AND_FAULTS_CHOICE (2u)
#define POWERTRAIN_INVERTER_TELEMETRY_INVERTER_STATE_OFF_CHOICE (0u)
#define POWERTRAIN_INVERTER_TELEMETRY_INVERTER_STATE_STANDBY_CHOICE (1u)
#define POWERTRAIN_INVERTER_TELEMETRY_INVERTER_STATE_RUNNING_CHOICE (2u)
#define POWERTRAIN_INVERTER_TELEMETRY_INVERTER_STATE_DERATED_CHOICE (3u)
#define POWERTRAIN_INVERTER_TELEMETRY_INVERTER_STATE_FAULT_CHOICE (4u)
#define POWERTRAIN_WHEEL_SPEEDS_WHEEL_SPEED_VALID_NONE_CHOICE (0u)
#define POWERTRAIN_WHEEL_SPEEDS_WHEEL_SPEED_VALID_FRONT_ONLY_CHOICE (1u)
#define POWERTRAIN_WHEEL_SPEEDS_WHEEL_SPEED_VALID_REAR_ONLY_CHOICE (2u)
#define POWERTRAIN_WHEEL_SPEEDS_WHEEL_SPEED_VALID_ALL_CHOICE (3u)

/**
 * VehicleStatus
 *
 * Frame 0x100 (standard), 8 bytes, sent by VCU.
 * Core vehicle state, broadcast every 10 ms.
 */
typedef struct {
    /*
     * VehicleSpeed: 0|16@1+, scale 0.01, offset 0.0, range 0.0 to 655.35, unit
     * km/h. Vehicle speed derived from wheel speeds.
     */
    uint16_t vehicle_speed;
    /* GearPosition: 16|3@1+, scale 1.0, offset 0.0, range 0.0 to 7.0. */
    uint8_t gear_position;
    /* BrakePressed: 19|1@1+, scale 1.0, offset 0.0, range 0.0 to 1.0. */
    uint8_t brake_pressed;
    /* DriveMode: 20|2@1+, scale 1.0, offset 0.0, range 0.0 to 3.0. */
    uint8_t drive_mode;
    /*
     * AcceleratorPedal: 24|8@1+, scale 0.4, offset 0.0, range 0.0 to 100.0, unit
     * %.
     */
    uint8_t accelerator_pedal;
    /*
     * SteeringAngle: 32|16@1-, scale 0.1, offset 0.0, range -3276.8 to 3276.7,
     * unit deg.
     */
    int16_t steering_angle;
    /* RollingCounter: 56|4@1+, scale 1.0, offset 0.0, range 0.0 to 15.0. */
    uint8_t rolling_counter;
    /*
     * Checksum: 60|4@1+, scale 1.0, offset 0.0, range 0.0 to 15.0. XOR of the
     * first 7 bytes, low nibble.
     */
    uint8_t checksum;
} powertrain_vehicle_status_t;

/** Set every signal of VehicleStatus to raw zero. */
void powertrain_vehicle_status_init(powertrain_vehicle_status_t *msg_p);

/**
 * Pack VehicleStatus into dst_p, which must hold at least POWERTRAIN_VEHICLE_STATUS_LENGTH bytes.
 * Returns the number of bytes written, or -1 if size is too small.
 */
int powertrain_vehicle_status_pack(uint8_t *dst_p, const powertrain_vehicle_status_t *src_p, size_t size);

/**
 * Unpack VehicleStatus from src_p. Returns 0 on success, or -1 if size is
 * too small. Multiplexed signals outside the active group are zero.
 */
int powertrain_vehicle_status_unpack(powertrain_vehicle_status_t *dst_p, const uint8_t *src_p, size_t size);

double powertrain_vehicle_status_vehicle_speed_decode(uint16_t raw);
uint16_t powertrain_vehicle_status_vehicle_speed_encode(double value);
bool powertrain_vehicle_status_vehicle_speed_is_in_range(uint16_t raw);

double powertrain_vehicle_status_gear_position_decode(uint8_t raw);
uint8_t powertrain_vehicle_status_gear_position_encode(double value);
bool powertrain_vehicle_status_gear_position_is_in_range(uint8_t raw);

double powertrain_vehicle_status_brake_pressed_decode(uint8_t raw);
uint8_t powertrain_vehicle_status_brake_pressed_encode(double value);
bool powertrain_vehicle_status_brake_pressed_is_in_range(uint8_t raw);

double powertrain_vehicle_status_drive_mode_decode(uint8_t raw);
uint8_t powertrain_vehicle_status_drive_mode_encode(double value);
bool powertrain_vehicle_status_drive_mode_is_in_range(uint8_t raw);

double powertrain_vehicle_status_accelerator_pedal_decode(uint8_t raw);
uint8_t powertrain_vehicle_status_accelerator_pedal_encode(double value);
bool powertrain_vehicle_status_accelerator_pedal_is_in_range(uint8_t raw);

double powertrain_vehicle_status_steering_angle_decode(int16_t raw);
int16_t powertrain_vehicle_status_steering_angle_encode(double value);
bool powertrain_vehicle_status_steering_angle_is_in_range(int16_t raw);

double powertrain_vehicle_status_rolling_counter_decode(uint8_t raw);
uint8_t powertrain_vehicle_status_rolling_counter_encode(double value);
bool powertrain_vehicle_status_rolling_counter_is_in_range(uint8_t raw);

double powertrain_vehicle_status_checksum_decode(uint8_t raw);
uint8_t powertrain_vehicle_status_checksum_encode(double value);
bool powertrain_vehicle_status_checksum_is_in_range(uint8_t raw);

/**
 * BatteryStatus
 *
 * Frame 0x200 (standard), 8 bytes, sent by BMS.
 * Pack-level battery measurements.
 */
typedef struct {
    /* PackVoltage: 7|16@0+, scale 0.01, offset 0.0, range 0.0 to 655.35, unit V. */
    uint16_t pack_voltage;
    /*
     * PackCurrent: 23|16@0-, scale 0.05, offset 0.0, range -1638.4 to 1638.35,
     * unit A. Positive values discharge the pack, negative values charge it.
     */
    int16_t pack_current;
    /* StateOfCharge: 39|8@0+, scale 0.5, offset 0.0, range 0.0 to 100.0, unit %. */
    uint8_t state_of_charge;
    /*
     * MaxCellTemp: 47|8@0-, scale 1.0, offset 0.0, range -40.0 to 85.0, unit
     * degC.
     */
    int8_t max_cell_temp;
    /* ContactorState: 55|2@0+, scale 1.0, offset 0.0, range 0.0 to 3.0. */
    uint8_t contactor_state;
    /* BalancingActive: 53|1@0+, scale 1.0, offset 0.0, range 0.0 to 1.0. */
    uint8_t balancing_active;
    /* CellCount: 52|5@0+, scale 1.0, offset 0.0, range 0.0 to 31.0. */
    uint8_t cell_count;
} powertrain_battery_status_t;

/** Set every signal of BatteryStatus to raw zero. */
void powertrain_battery_status_init(powertrain_battery_status_t *msg_p);

/**
 * Pack BatteryStatus into dst_p, which must hold at least POWERTRAIN_BATTERY_STATUS_LENGTH bytes.
 * Returns the number of bytes written, or -1 if size is too small.
 */
int powertrain_battery_status_pack(uint8_t *dst_p, const powertrain_battery_status_t *src_p, size_t size);

/**
 * Unpack BatteryStatus from src_p. Returns 0 on success, or -1 if size is
 * too small. Multiplexed signals outside the active group are zero.
 */
int powertrain_battery_status_unpack(powertrain_battery_status_t *dst_p, const uint8_t *src_p, size_t size);

double powertrain_battery_status_pack_voltage_decode(uint16_t raw);
uint16_t powertrain_battery_status_pack_voltage_encode(double value);
bool powertrain_battery_status_pack_voltage_is_in_range(uint16_t raw);

double powertrain_battery_status_pack_current_decode(int16_t raw);
int16_t powertrain_battery_status_pack_current_encode(double value);
bool powertrain_battery_status_pack_current_is_in_range(int16_t raw);

double powertrain_battery_status_state_of_charge_decode(uint8_t raw);
uint8_t powertrain_battery_status_state_of_charge_encode(double value);
bool powertrain_battery_status_state_of_charge_is_in_range(uint8_t raw);

double powertrain_battery_status_max_cell_temp_decode(int8_t raw);
int8_t powertrain_battery_status_max_cell_temp_encode(double value);
bool powertrain_battery_status_max_cell_temp_is_in_range(int8_t raw);

double powertrain_battery_status_contactor_state_decode(uint8_t raw);
uint8_t powertrain_battery_status_contactor_state_encode(double value);
bool powertrain_battery_status_contactor_state_is_in_range(uint8_t raw);

double powertrain_battery_status_balancing_active_decode(uint8_t raw);
uint8_t powertrain_battery_status_balancing_active_encode(double value);
bool powertrain_battery_status_balancing_active_is_in_range(uint8_t raw);

double powertrain_battery_status_cell_count_decode(uint8_t raw);
uint8_t powertrain_battery_status_cell_count_encode(double value);
bool powertrain_battery_status_cell_count_is_in_range(uint8_t raw);

/**
 * InverterTelemetry
 *
 * Frame 0x300 (standard), 8 bytes, sent by INVERTER.
 * Inverter telemetry. PageIndex selects which signals are present.
 */
typedef struct {
    /* PageIndex: 0|8@1+, scale 1.0, offset 0.0, range 0.0 to 2.0. */
    uint8_t page_index;
    /*
     * MotorSpeed: 8|16@1-, scale 1.0, offset 0.0, range -20000.0 to 20000.0,
     * unit rpm.
     */
    int16_t motor_speed;
    /*
     * MotorTorque: 24|16@1-, scale 0.1, offset 0.0, range -500.0 to 500.0, unit
     * Nm.
     */
    int16_t motor_torque;
    /*
     * StatorTemp: 8|8@1+, scale 1.0, offset -40.0, range -40.0 to 215.0, unit
     * degC.
     */
    uint8_t stator_temp;
    /*
     * IgbtTemp: 16|8@1+, scale 1.0, offset -40.0, range -40.0 to 215.0, unit
     * degC.
     */
    uint8_t igbt_temp;
    /*
     * DcLinkVoltage: 8|16@1+, scale 0.1, offset 0.0, range 0.0 to 1000.0, unit
     * V.
     */
    uint16_t dc_link_voltage;
    /* FaultCode: 24|16@1+, scale 1.0, offset 0.0, range 0.0 to 65535.0. */
    uint16_t fault_code;
    /* InverterState: 56|3@1+, scale 1.0, offset 0.0, range 0.0 to 7.0. */
    uint8_t inverter_state;
} powertrain_inverter_telemetry_t;

/** Set every signal of InverterTelemetry to raw zero. */
void powertrain_inverter_telemetry_init(powertrain_inverter_telemetry_t *msg_p);

/**
 * Pack InverterTelemetry into dst_p, which must hold at least POWERTRAIN_INVERTER_TELEMETRY_LENGTH bytes.
 * Returns the number of bytes written, or -1 if size is too small.
 */
int powertrain_inverter_telemetry_pack(uint8_t *dst_p, const powertrain_inverter_telemetry_t *src_p, size_t size);

/**
 * Unpack InverterTelemetry from src_p. Returns 0 on success, or -1 if size is
 * too small. Multiplexed signals outside the active group are zero.
 */
int powertrain_inverter_telemetry_unpack(powertrain_inverter_telemetry_t *dst_p, const uint8_t *src_p, size_t size);

double powertrain_inverter_telemetry_page_index_decode(uint8_t raw);
uint8_t powertrain_inverter_telemetry_page_index_encode(double value);
bool powertrain_inverter_telemetry_page_index_is_in_range(uint8_t raw);

double powertrain_inverter_telemetry_motor_speed_decode(int16_t raw);
int16_t powertrain_inverter_telemetry_motor_speed_encode(double value);
bool powertrain_inverter_telemetry_motor_speed_is_in_range(int16_t raw);

double powertrain_inverter_telemetry_motor_torque_decode(int16_t raw);
int16_t powertrain_inverter_telemetry_motor_torque_encode(double value);
bool powertrain_inverter_telemetry_motor_torque_is_in_range(int16_t raw);

double powertrain_inverter_telemetry_stator_temp_decode(uint8_t raw);
uint8_t powertrain_inverter_telemetry_stator_temp_encode(double value);
bool powertrain_inverter_telemetry_stator_temp_is_in_range(uint8_t raw);

double powertrain_inverter_telemetry_igbt_temp_decode(uint8_t raw);
uint8_t powertrain_inverter_telemetry_igbt_temp_encode(double value);
bool powertrain_inverter_telemetry_igbt_temp_is_in_range(uint8_t raw);

double powertrain_inverter_telemetry_dc_link_voltage_decode(uint16_t raw);
uint16_t powertrain_inverter_telemetry_dc_link_voltage_encode(double value);
bool powertrain_inverter_telemetry_dc_link_voltage_is_in_range(uint16_t raw);

double powertrain_inverter_telemetry_fault_code_decode(uint16_t raw);
uint16_t powertrain_inverter_telemetry_fault_code_encode(double value);
bool powertrain_inverter_telemetry_fault_code_is_in_range(uint16_t raw);

double powertrain_inverter_telemetry_inverter_state_decode(uint8_t raw);
uint8_t powertrain_inverter_telemetry_inverter_state_encode(double value);
bool powertrain_inverter_telemetry_inverter_state_is_in_range(uint8_t raw);

/**
 * ChargerLimits
 *
 * Frame 0x18FF50E5 (extended), 8 bytes, sent by GATEWAY.
 * J1939-style charger limits on a 29-bit identifier.
 */
typedef struct {
    /*
     * ChargeCurrentLimit: 0|16@1+, scale 0.1, offset 0.0, range 0.0 to 6553.5,
     * unit A.
     */
    uint16_t charge_current_limit;
    /*
     * ChargeVoltageLimit: 16|16@1+, scale 0.1, offset 0.0, range 0.0 to 6553.5,
     * unit V.
     */
    uint16_t charge_voltage_limit;
    /* ChargerEnable: 32|1@1+, scale 1.0, offset 0.0, range 0.0 to 1.0. */
    uint8_t charger_enable;
} powertrain_charger_limits_t;

/** Set every signal of ChargerLimits to raw zero. */
void powertrain_charger_limits_init(powertrain_charger_limits_t *msg_p);

/**
 * Pack ChargerLimits into dst_p, which must hold at least POWERTRAIN_CHARGER_LIMITS_LENGTH bytes.
 * Returns the number of bytes written, or -1 if size is too small.
 */
int powertrain_charger_limits_pack(uint8_t *dst_p, const powertrain_charger_limits_t *src_p, size_t size);

/**
 * Unpack ChargerLimits from src_p. Returns 0 on success, or -1 if size is
 * too small. Multiplexed signals outside the active group are zero.
 */
int powertrain_charger_limits_unpack(powertrain_charger_limits_t *dst_p, const uint8_t *src_p, size_t size);

double powertrain_charger_limits_charge_current_limit_decode(uint16_t raw);
uint16_t powertrain_charger_limits_charge_current_limit_encode(double value);
bool powertrain_charger_limits_charge_current_limit_is_in_range(uint16_t raw);

double powertrain_charger_limits_charge_voltage_limit_decode(uint16_t raw);
uint16_t powertrain_charger_limits_charge_voltage_limit_encode(double value);
bool powertrain_charger_limits_charge_voltage_limit_is_in_range(uint16_t raw);

double powertrain_charger_limits_charger_enable_decode(uint8_t raw);
uint8_t powertrain_charger_limits_charger_enable_encode(double value);
bool powertrain_charger_limits_charger_enable_is_in_range(uint8_t raw);

/**
 * ThermalSensors
 *
 * Frame 0x400 (standard), 8 bytes, sent by BMS.
 */
typedef struct {
    /*
     * CoolantFlow: 0|32@1-, float32, scale 1.0, offset 0.0, range 0.0 to 100.0,
     * unit L/min. IEEE 754 single-precision value.
     */
    uint32_t coolant_flow;
    /*
     * AmbientTemp: 32|32@1-, float32, scale 1.0, offset 0.0, range -50.0 to
     * 80.0, unit degC.
     */
    uint32_t ambient_temp;
} powertrain_thermal_sensors_t;

/** Set every signal of ThermalSensors to raw zero. */
void powertrain_thermal_sensors_init(powertrain_thermal_sensors_t *msg_p);

/**
 * Pack ThermalSensors into dst_p, which must hold at least POWERTRAIN_THERMAL_SENSORS_LENGTH bytes.
 * Returns the number of bytes written, or -1 if size is too small.
 */
int powertrain_thermal_sensors_pack(uint8_t *dst_p, const powertrain_thermal_sensors_t *src_p, size_t size);

/**
 * Unpack ThermalSensors from src_p. Returns 0 on success, or -1 if size is
 * too small. Multiplexed signals outside the active group are zero.
 */
int powertrain_thermal_sensors_unpack(powertrain_thermal_sensors_t *dst_p, const uint8_t *src_p, size_t size);

double powertrain_thermal_sensors_coolant_flow_decode(uint32_t raw);
uint32_t powertrain_thermal_sensors_coolant_flow_encode(double value);
bool powertrain_thermal_sensors_coolant_flow_is_in_range(uint32_t raw);

double powertrain_thermal_sensors_ambient_temp_decode(uint32_t raw);
uint32_t powertrain_thermal_sensors_ambient_temp_encode(double value);
bool powertrain_thermal_sensors_ambient_temp_is_in_range(uint32_t raw);

/**
 * WheelSpeeds
 *
 * Frame 0x600 (standard), 8 bytes, sent by GATEWAY.
 */
typedef struct {
    /*
     * WheelSpeedFL: 7|12@0+, scale 0.1, offset 0.0, range 0.0 to 409.5, unit
     * km/h.
     */
    uint16_t wheel_speed_fl;
    /*
     * WheelSpeedFR: 11|12@0+, scale 0.1, offset 0.0, range 0.0 to 409.5, unit
     * km/h.
     */
    uint16_t wheel_speed_fr;
    /*
     * WheelSpeedRL: 31|12@0+, scale 0.1, offset 0.0, range 0.0 to 409.5, unit
     * km/h.
     */
    uint16_t wheel_speed_rl;
    /*
     * WheelSpeedRR: 35|12@0+, scale 0.1, offset 0.0, range 0.0 to 409.5, unit
     * km/h.
     */
    uint16_t wheel_speed_rr;
    /*
     * YawRate: 48|14@1-, scale 0.01, offset 0.0, range -81.92 to 81.91, unit
     * deg/s.
     */
    int16_t yaw_rate;
    /* WheelSpeedValid: 62|2@1+, scale 1.0, offset 0.0, range 0.0 to 3.0. */
    uint8_t wheel_speed_valid;
} powertrain_wheel_speeds_t;

/** Set every signal of WheelSpeeds to raw zero. */
void powertrain_wheel_speeds_init(powertrain_wheel_speeds_t *msg_p);

/**
 * Pack WheelSpeeds into dst_p, which must hold at least POWERTRAIN_WHEEL_SPEEDS_LENGTH bytes.
 * Returns the number of bytes written, or -1 if size is too small.
 */
int powertrain_wheel_speeds_pack(uint8_t *dst_p, const powertrain_wheel_speeds_t *src_p, size_t size);

/**
 * Unpack WheelSpeeds from src_p. Returns 0 on success, or -1 if size is
 * too small. Multiplexed signals outside the active group are zero.
 */
int powertrain_wheel_speeds_unpack(powertrain_wheel_speeds_t *dst_p, const uint8_t *src_p, size_t size);

double powertrain_wheel_speeds_wheel_speed_fl_decode(uint16_t raw);
uint16_t powertrain_wheel_speeds_wheel_speed_fl_encode(double value);
bool powertrain_wheel_speeds_wheel_speed_fl_is_in_range(uint16_t raw);

double powertrain_wheel_speeds_wheel_speed_fr_decode(uint16_t raw);
uint16_t powertrain_wheel_speeds_wheel_speed_fr_encode(double value);
bool powertrain_wheel_speeds_wheel_speed_fr_is_in_range(uint16_t raw);

double powertrain_wheel_speeds_wheel_speed_rl_decode(uint16_t raw);
uint16_t powertrain_wheel_speeds_wheel_speed_rl_encode(double value);
bool powertrain_wheel_speeds_wheel_speed_rl_is_in_range(uint16_t raw);

double powertrain_wheel_speeds_wheel_speed_rr_decode(uint16_t raw);
uint16_t powertrain_wheel_speeds_wheel_speed_rr_encode(double value);
bool powertrain_wheel_speeds_wheel_speed_rr_is_in_range(uint16_t raw);

double powertrain_wheel_speeds_yaw_rate_decode(int16_t raw);
int16_t powertrain_wheel_speeds_yaw_rate_encode(double value);
bool powertrain_wheel_speeds_yaw_rate_is_in_range(int16_t raw);

double powertrain_wheel_speeds_wheel_speed_valid_decode(uint8_t raw);
uint8_t powertrain_wheel_speeds_wheel_speed_valid_encode(double value);
bool powertrain_wheel_speeds_wheel_speed_valid_is_in_range(uint8_t raw);

/**
 * DiagnosticFD
 *
 * Frame 0x500 (standard), 64 bytes, sent by GATEWAY.
 * Diagnostic snapshot carried on a 64-byte CAN FD frame.
 */
typedef struct {
    /*
     * Odometer: 0|32@1+, scale 0.1, offset 0.0, range 0.0 to 429496729.5, unit
     * km.
     */
    uint32_t odometer;
    /* TripId: 32|32@1+, scale 1.0, offset 0.0, range 0.0 to 4294967295.0. */
    uint32_t trip_id;
    /* SerialNumber: 64|64@1+, scale 1.0, offset 0.0. */
    uint64_t serial_number;
    /* FirmwareCrc: 128|32@1+, scale 1.0, offset 0.0. */
    uint32_t firmware_crc;
    /* LifetimeEnergy: 191|48@0+, scale 0.001, offset 0.0, unit kWh. */
    uint64_t lifetime_energy;
    /* TimestampNs: 256|64@1-, scale 1.0, offset 0.0, unit ns. */
    int64_t timestamp_ns;
} powertrain_diagnostic_fd_t;

/** Set every signal of DiagnosticFD to raw zero. */
void powertrain_diagnostic_fd_init(powertrain_diagnostic_fd_t *msg_p);

/**
 * Pack DiagnosticFD into dst_p, which must hold at least POWERTRAIN_DIAGNOSTIC_FD_LENGTH bytes.
 * Returns the number of bytes written, or -1 if size is too small.
 */
int powertrain_diagnostic_fd_pack(uint8_t *dst_p, const powertrain_diagnostic_fd_t *src_p, size_t size);

/**
 * Unpack DiagnosticFD from src_p. Returns 0 on success, or -1 if size is
 * too small. Multiplexed signals outside the active group are zero.
 */
int powertrain_diagnostic_fd_unpack(powertrain_diagnostic_fd_t *dst_p, const uint8_t *src_p, size_t size);

double powertrain_diagnostic_fd_odometer_decode(uint32_t raw);
uint32_t powertrain_diagnostic_fd_odometer_encode(double value);
bool powertrain_diagnostic_fd_odometer_is_in_range(uint32_t raw);

double powertrain_diagnostic_fd_trip_id_decode(uint32_t raw);
uint32_t powertrain_diagnostic_fd_trip_id_encode(double value);
bool powertrain_diagnostic_fd_trip_id_is_in_range(uint32_t raw);

double powertrain_diagnostic_fd_serial_number_decode(uint64_t raw);
uint64_t powertrain_diagnostic_fd_serial_number_encode(double value);
bool powertrain_diagnostic_fd_serial_number_is_in_range(uint64_t raw);

double powertrain_diagnostic_fd_firmware_crc_decode(uint32_t raw);
uint32_t powertrain_diagnostic_fd_firmware_crc_encode(double value);
bool powertrain_diagnostic_fd_firmware_crc_is_in_range(uint32_t raw);

double powertrain_diagnostic_fd_lifetime_energy_decode(uint64_t raw);
uint64_t powertrain_diagnostic_fd_lifetime_energy_encode(double value);
bool powertrain_diagnostic_fd_lifetime_energy_is_in_range(uint64_t raw);

double powertrain_diagnostic_fd_timestamp_ns_decode(int64_t raw);
int64_t powertrain_diagnostic_fd_timestamp_ns_encode(double value);
bool powertrain_diagnostic_fd_timestamp_ns_is_in_range(int64_t raw);

#ifdef __cplusplus
}
#endif

#endif /* POWERTRAIN_H */
