//! Python decoder generation: a dependency-free module with one decode_*
//! function per message, for test benches and log analysis.

use crate::bits::segments;
use crate::codegen_c::{comment_text, require_clean, scale_expr, split_groups};
use crate::model::{Database, Signal, ValueType};
use crate::names::Names;
use crate::{PROJECT_URL, VERSION};

/// A Python string literal, escaped like `json.dumps(s, ensure_ascii=True)`.
fn py_str(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 || (c as u32) > 0x7F => {
                let mut buf = [0u16; 2];
                for unit in c.encode_utf16(&mut buf).iter() {
                    out.push_str(&format!("\\u{:04x}", unit));
                }
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn unpack_lines(s: &Signal, indent: &str) -> Vec<String> {
    let mut lines: Vec<String> = Vec::new();
    lines.push(format!("{}v = 0", indent));
    for seg in segments(s).iter() {
        let mut term = format!("data[{}]", seg.byte);
        if seg.byte_bit_lo > 0 {
            term = format!("({} >> {})", term, seg.byte_bit_lo);
        }
        if seg.count < 8 {
            term = format!("({} & 0x{:X})", term, (1u32 << seg.count) - 1);
        }
        if seg.raw_bit_lo > 0 {
            term = format!("({} << {})", term, seg.raw_bit_lo);
        }
        lines.push(format!("{}v |= {}", indent, term));
    }
    if s.value_type == ValueType::Integer && s.signed {
        let sign: u128 = 1u128 << (s.length - 1);
        let full: u128 = 1u128 << s.length;
        lines.push(format!("{}if v & 0x{:X}:", indent, sign));
        lines.push(format!("{}    v -= 0x{:X}", indent, full));
    }
    lines
}

fn value_expr(s: &Signal) -> String {
    let base = match s.value_type {
        ValueType::Float32 => "struct.unpack(\"<f\", v.to_bytes(4, \"little\"))[0]",
        ValueType::Float64 => "struct.unpack(\"<d\", v.to_bytes(8, \"little\"))[0]",
        ValueType::Integer => {
            if s.factor == 1.0 {
                "float(v)"
            } else {
                "v"
            }
        }
    };
    scale_expr(base, s)
}

/// Generate the source of `prefix.py`.
pub fn generate(db: &Database, _prefix: &str, source_name: &str) -> Result<String, String> {
    require_clean(db)?;
    let names = Names::new(db);
    let mut out: Vec<String> = Vec::new();
    out.push(format!(
        "\"\"\"Decoders for {}.",
        comment_text(source_name).replace('"', "'")
    ));
    out.push(String::new());
    out.push(format!("Generated by canforge {}. Do not edit.", VERSION));
    out.push(PROJECT_URL.to_string());
    out.push(String::new());
    out.push("Each decode_* function takes the frame payload as bytes and returns a".to_string());
    out.push("dict of physical values keyed by signal name. Multiplexed signals are".to_string());
    out.push("only present when their multiplexer selects them.".to_string());
    out.push("\"\"\"".to_string());
    out.push(String::new());
    out.push("import struct".to_string());
    out.push(String::new());
    out.push(String::new());
    out.push("class DecodeError(ValueError):".to_string());
    out.push("    \"\"\"Raised when a frame cannot be decoded.\"\"\"".to_string());

    let mut entries: Vec<(usize, String)> = Vec::new();
    for (mi, m) in db.messages.iter().enumerate() {
        let fname = format!("decode_{}", names.msg[mi]);
        entries.push((mi, fname.clone()));
        let g = split_groups(m);
        out.push(String::new());
        out.push(String::new());
        out.push(format!("def {}(data):", fname));
        let fmt = if m.is_extended { "extended" } else { "standard" };
        out.push(format!(
            "    \"\"\"Decode {} (frame 0x{:X}, {}, {} bytes).\"\"\"",
            comment_text(&m.name),
            m.frame_id,
            fmt,
            m.dlc
        ));
        if m.dlc > 0 {
            out.push(format!("    if len(data) < {}:", m.dlc));
            out.push(format!(
                "        raise DecodeError(\"{} needs {} bytes, got %d\" % len(data))",
                m.name, m.dlc
            ));
        }
        out.push("    values = {}".to_string());
        for &si in g.plain.iter() {
            let s = &m.signals[si];
            out.extend(unpack_lines(s, "    "));
            if g.mux == Some(si) {
                out.push("    mux = v".to_string());
            }
            out.push(format!("    values[{}] = {}", py_str(&s.name), value_expr(s)));
        }
        for (gi, (value, members)) in g.groups.iter().enumerate() {
            let keyword = if gi == 0 { "if" } else { "elif" };
            out.push(format!("    {} mux == {}:", keyword, value));
            for &si in members.iter() {
                let s = &m.signals[si];
                out.extend(unpack_lines(s, "        "));
                out.push(format!("        values[{}] = {}", py_str(&s.name), value_expr(s)));
            }
        }
        out.push("    return values".to_string());
    }

    out.push(String::new());
    out.push(String::new());
    out.push("DECODERS = {".to_string());
    for (mi, fname) in entries.iter() {
        let m = &db.messages[*mi];
        out.push(format!(
            "    (0x{:X}, {}): {},",
            m.frame_id,
            if m.is_extended { "True" } else { "False" },
            fname
        ));
    }
    out.push("}".to_string());
    out.push(String::new());
    out.push("MESSAGE_NAMES = {".to_string());
    for (mi, _) in entries.iter() {
        let m = &db.messages[*mi];
        out.push(format!(
            "    (0x{:X}, {}): {},",
            m.frame_id,
            if m.is_extended { "True" } else { "False" },
            py_str(&m.name)
        ));
    }
    out.push("}".to_string());
    out.push(String::new());
    out.push(String::new());
    out.push("def decode(frame_id, data, is_extended=False):".to_string());
    out.push("    \"\"\"Decode a frame by ID. Raises DecodeError for unknown frames.\"\"\"".to_string());
    out.push("    fn = DECODERS.get((frame_id, is_extended))".to_string());
    out.push("    if fn is None:".to_string());
    out.push("        raise DecodeError(\"unknown frame ID 0x%X\" % frame_id)".to_string());
    out.push("    return fn(bytes(data))".to_string());
    out.push(String::new());
    Ok(out.join("\n"))
}
